Fix build with liburcu-0.15.0
:Release Notes:
Fix build error

:Detailed Notes:
Fixes:
http://gecko.lge.com:8000/Errors/Details/1095642

FAILED: src/core/trace/CMakeFiles/WebAppMgrTrace.dir/web_app_manager_tracer_lib.cc.o
...
In file included from TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/wam-clang/1.0.2-99/git/src/core/trace/web_app_manager_tracer_lib.cc:19:
In file included from TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/wam-clang/1.0.2-99/git/src/core/trace/pmtrace_webappmanager3_provider.h:31:
In file included from TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/wam-clang/1.0.2-99/recipe-sysroot/usr/include/lttng/tracepoint.h:13:
In file included from TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/wam-clang/1.0.2-99/recipe-sysroot/usr/include/lttng/tracepoint-rcu.h:10:
TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/wam-clang/1.0.2-99/recipe-sysroot/usr/include/urcu/compiler.h:205:1: error: templates must have C++ linkage

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRR-17603] Fix build with liburcu-0.15.0

Change-Id: I7467077afb1f7ab27bd75bd70426071c5b82fe32